# default initial positions of all 7 joints

initial_positions:
  joint1_base_yaw: 0
  joint2_shoulder_pitch: 0
  joint3_shoulder_roll: 0
  joint4_elbow_pitch: 0
  joint5_wrist_yaw: 0
  joint6_wrist_pitch: 0
  joint7_wrist_roll: 0
