#my_group is the planning group as specified in the moveit setup assistant. It uses KDL kinematics and LazyPRMstar 
my_group:
  tip_frame: end_effector
  kinematics_solver: kdl_kinematics_plugin/KDLKinematicsPlugin
  kinematics_solver_search_resolution: 0.0050000000000000001
  kinematics_solver_timeout: 0.5
