

moveit_controller_manager: moveit_simple_controller_manager/MoveItSimpleControllerManager

# my_group_controller is sourced from moveit_simple_controller_manager

moveit_simple_controller_manager:
  controller_names:
    - my_group_controller
    
  #my_group_controller is of type FollowJointTrajectory - it receives a trajectory and follows it
  
  my_group_controller:
    type: FollowJointTrajectory
    action_ns: follow_joint_trajectory
    default: true
    joints:
      - joint1_base_yaw
      - joint2_shoulder_pitch
      - joint3_shoulder_roll
      - joint4_elbow_pitch
      - joint5_wrist_yaw
      - joint6_wrist_pitch
      - joint7_wrist_roll
